### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [MelisandeF/prj-rev-bwfs-dasmoto#5]
Grade: Needs Improvement

Summary:
Melisande, excellent job getting the Dasmoto's Arts & Crafts completed! Everything looked to be following the spec guidelines. Some things you can improve on, so you become a great web developer are your HTML structure and indenting. As your projects increase in size having correct structure and indentation will allow you to read your HTML code easily. 

To keep practicing try implementing the recommendations I gave! I'm sure you will learn a lot making those changes and as you continue with future lessons!

**Comment by MelisandeF** [comment]
Hello Jim 
Thank's a lot for theses comments, which will be very usefull for my learning and my execution. Thank's for your time!
I will work a lot to improve my code !
